version: "3"
services:
  hotel:
    image: mario21ic/nginx:prod
    #environment:
    #  - PARALLEL_WORK_ACTIVE=0
    #volumes:
      #- ~/.aws/credentials:/root/.aws/credentials:rw
      #- "logs_nginx:/var/log/nginx/"
    ports:
      - 80:80
    # service deployment
    deploy:
      # replicated or global
      mode: replicated
      replicas: 2
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '1'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.50'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
      # service update configuration
      update_config:
        parallelism: 2
      # placement constraint - 'worker' or 'manager'
      placement:
        constraints: [node.role == manager]

#volumes:
#  logs_nginx:
